#!/usr/bin/env python3
"""Regenerate docs/SOURCES.md — the registry of pinned commits per repository.

Reads every citation in the collection and reports, per repository, which
commit SHAs are in use and which notes cite them. A repository pinned at more
than one SHA is not an error, but it is worth knowing: a batch of notes written
in one sweep should normally share a snapshot.

Usage:
    python3 tools/sources_index.py           # rewrite docs/SOURCES.md
    python3 tools/sources_index.py --check   # fail if the file is out of date
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import zklib  # noqa: E402

OUT_PATH = os.path.join(zklib.REPO_ROOT, "docs", "SOURCES.md")

HEADER = """# Pinned sources

Every citation in this collection points at a **Dans-Plugins** repository at a
specific commit SHA. This file is the index of those pins, regenerated by
`python3 tools/sources_index.py`.

When adding notes, prefer an existing pin for a repository over a fresh one, so
a reader comparing two notes about the same code is comparing the same code.
Re-pin deliberately — as a sweep, after `tools/check_sources.py` reports drift —
rather than incidentally.

"""


def build():
    notes = zklib.load_notes()
    repos = {}
    for note in notes:
        for source in note.sources:
            by_ref = repos.setdefault(source["repo"], {})
            entry = by_ref.setdefault(source["ref"], {"notes": set(), "paths": set()})
            entry["notes"].add(note.id)
            entry["paths"].add(source["path"])

    lines = [HEADER]
    lines.append("| Repository | Pinned commit | Files cited | Notes |")
    lines.append("|---|---|---|---|")
    for repo in sorted(repos):
        for ref in sorted(repos[repo]):
            entry = repos[repo][ref]
            lines.append(
                "| [%s](https://github.com/%s) | [`%s`](https://github.com/%s/tree/%s) | %d | %d |"
                % (repo, repo, ref[:10], repo, ref, len(entry["paths"]), len(entry["notes"]))
            )

    total_pins = sum(len(v) for v in repos.values())
    lines.append("")
    lines.append(
        "%d repositories, %d pinned commits, %d citations across %d notes."
        % (
            len(repos),
            total_pins,
            sum(len(n.sources) for n in notes),
            sum(1 for n in notes if n.sources),
        )
    )

    multi = [r for r, v in repos.items() if len(v) > 1]
    if multi:
        lines.append("")
        lines.append("> Pinned at more than one commit: %s." % ", ".join(sorted(multi)))

    lines.append("")
    lines.append("## Cited files by repository")
    lines.append("")
    for repo in sorted(repos):
        lines.append("### %s" % repo)
        lines.append("")
        for ref in sorted(repos[repo]):
            entry = repos[repo][ref]
            lines.append("At `%s`:" % ref)
            lines.append("")
            for path in sorted(entry["paths"]):
                lines.append(
                    "- [`%s`](https://github.com/%s/blob/%s/%s)" % (path, repo, ref, path)
                )
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if docs/SOURCES.md differs from what would be written")
    args = parser.parse_args()

    try:
        content = build()
    except zklib.NoteError as exc:
        zklib.fail(str(exc))

    if args.check:
        existing = ""
        if os.path.exists(OUT_PATH):
            with open(OUT_PATH, "r", encoding="utf-8") as handle:
                existing = handle.read()
        if existing != content:
            sys.stderr.write("docs/SOURCES.md is out of date; run tools/sources_index.py\n")
            return 1
        print("docs/SOURCES.md is up to date")
        return 0

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(content)
    print("wrote docs/SOURCES.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
